# +--------------------------------------------------------------------------+ #
# <                     PvPManager Configuration File                        > #
# <--------------------------------------------------------------------------> #
# <               For help understanding a config option go to               > #
# <            https://www.spigotmc.org/threads/pvpmanager.25420/            > #
# <                  or Discord https://discord.gg/w7gyBuw                   > #
# +--------------------------------------------------------------------------+ #

# Default PvP -> Leave it at true unless you want no PvP for new players
# PvP Blood -> Enable blood particles on PvP
# Player Drop Mode -> What happens to a player's drops and exp on death
# The options are 'ALWAYS' - (PvPManager does nothing, so feature is disabled),
# mode 'DROP' - (Players drop items when killed in PvP but not in PvE),
# mode 'KEEP' - (Players keep items when killed in PvP but not in PvE) and
# mode 'TRANSFER' - (Same as 'DROP' but transfer items(not exp) directly to killer's inventory without drops)
# mode 'CLEAR' - (Clear all drops and exp on death, this deletes everything on death so make sure it is what you want)
# Ignore No Damage Hits -> Ignore hits from snowballs, eggs, fishing rod and others
# World Exclusions -> List of worlds where PvPManager will have no effect
General:
  # Changes messages language, options are - EN | BG | DE | ES | FI | FR | HR | IT | JA | KO | PL | pt_BR | RU | TR | zh_TW | ZH
  Locale: EN
  Default PvP: true
  PvP Blood: true
  Player Drop Mode: ALWAYS
  Ignore No Damage Hits: true
  Auto Soup:
     # How much health does soup heal, use 0 to disable
     Health: 0
     # Should empty bowls just be deleted
     Bowl Disappear: false
  # Removes empty potion bottles and milk buckets after they are consumed
  Recycling:
    Potion Bottle: false
    Milk Bucket: false
  World Exclusions:
    - 'example'
    
# Here you can choose which methods to use to stop 'border hopping' while players are tagged
# Border hopping is when a player gets in PvP and tries to run into a safe zone to escape
# Vulnerable -> Makes players still vulnerable to PvP in safe zones
# Push Back -> Players will be launched back when trying to enter a safe zone
# Reset Combat Tag -> Only meant for when Vulnerable is true. Toggles whether combat tagging resets while fighting in a safe zone. Works for WorldGuard Only
Anti Border Hopping:
  Vulnerable: true
  Push Back:
    Enabled: true
    # Takes elytra from player chest slot and puts it in their inventory
    Remove Elytra: false
  Reset Combat Tag: true

# What should be disabled when a player(except operators) enters PvP
# Fly -> Disable any kind of fly mode
# GameMode -> Anything not Survival gets disabled
# Disguise -> Disguises from LibsDisguises
# GodMode -> GodMode from Essentials or CommandBook
# Invisibility -> Invisibility potions, defaults to false as it's a vanilla feature
Disable:
  Fly: true
  GameMode: true
  Disguise: true
  GodMode: true
  # Makes player fall down if they're tagged while elytra gliding
  Elytra: false
  Invisibility: false

# Section about the combat tag system
# Time -> How long should the tag last in seconds
# NameTag Prefix -> Choose the player's nametag prefix while tagged, '&c' would just color their name red
# while empty quotes '' will disable this feature completely
# Glowing -> For 1.9+ only, sets the player glowing while tagged
# Self Tag -> Allow players to tag themselves with a bow
# Untag Enemy -> When the player kills the enemy he was fighting he gets untagged
# Block -> Section is self-explanatory, what to block in combat
# Command whitelist is recursive, allowing 'tell' will allow 'tell' with any number of arguments
# Punish On Kick -> Punish the player even if he gets kicked by other plugin while tagged
# Money Penalty -> Money lost on combat log, use less or equal to 1 for percentage like 0.05 for 5%, 1 for 100% (0 to disable)
# Log To File -> Logs all combat loggers to a file that you can read later
# Kill on Logout -> Should the player be killed and, if so, what will he drop
# Commands On PvPLog -> List of commands to execute on combat log, use '%p' for player name
# And use the 'announce' command to broadcast, to disable just delete the command
Tagged In Combat:
  Enabled: true
  Time: 10
  NameTag Prefix: '&4&lCombat &c'
  # Currently only on premium version and when using the TAB plugin
  NameTag Suffix: ''
  Glowing: true
  # Symbol to use for the bar and how many times to repeat it. Other symbols ▊,▮,▯,|
  Action Bar:
    Enabled: true
    # You can use any PlaceholderAPI placeholders here
    Message: '&b&lCombat &a<barsLeft>&c<barsPassed> &e&l<time> &b[sec]'
    Symbol: '▊'
    Total Bars: 20
  Boss Bar:
    Enabled: true
    # You can use any PlaceholderAPI placeholders here
    Message: '&8&l[&c&lIn Combat&8&l] &e&l<time> seconds'
    # See here for bar color options - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
    BarColor: RED
    # See here for bar style options - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
    BarStyle: SOLID
  Self Tag: false
  Untag Enemy: false
  EnderPearl:
    # Time in seconds before the player can throw another enderpearl
    Cooldown: 10
    # If enabled, will retag the player when they throw an enderpearl
    Renew Tag: true
  Block:
    EnderPearls: false
    ChorusFruits: false
    Teleport: true
    Place Blocks: false
    Break Blocks: false
    Interact:
      Enabled: false
      # List of materials to block interaction, adding DOOR means all materials that end with DOOR like IRON_DOOR and so on
      List:
        - 'DOOR'
        - 'BUTTON'
        - 'BED'
        - 'SLAB'
        - 'STAIRS'
        - 'CARPET'
    Elytra: false
    Eat: false
    Totem of Undying: false
    Open Inventory: false
    Commands:
      Enabled: true
      Whitelist: true
      Command List:
        - 'tell'
        - 'combattag'
  Punishments:
    Punish On Kick:
      Enabled: true
      # If Match Kick Reason is enabled, the punishment will be applied only if the kick reason matches the list below
      Match Kick Reason: false
      Kick Reasons:
      - 'Kicked for spamming'
      - 'disconnect.spam'
    Money Penalty: 0.0
    Log To File: true
    Kill on Logout:
      Enabled: true
      Player Drops:
        Inventory: true
        Experience: true
        Armor: true
    Commands On PvPLog:
      - 'announce &6[&8PvPManager&6]&c %p tried to escape combat and died!'

# Should new players on your server be protected from PvP (If they want to PvP they can use /newbie disable)
Newbie Protection:
  Enabled: true
  # How many minutes should newbie protection last, persists through restarts
  Time(minutes): 5
  # If players should be allowed to remove their protection with /newbie disable
  Allow Player Disable: true
  # Block players from picking up items or place blocks while they have protection
  Block Pick Items: false
  Block Place Blocks: false
  Block Break Blocks: false
  # Protect newbies from all types of damage including PvE
  Protect From Everything: false
  Command Blacklist:
    - 'examplecommand'

# Prevent player abuse by killing the same player several times to rise in rank or even just grief
# Example - If a player X kills player Y more than 5 times, it executes the commands defined(kick, jail, etc)
# In this case, it would check every 30 seconds for abusers
# Respawn Protection - After respawn, how many seconds should players be protected (0 to disable)
Kill Abuse:
  Enabled: true
  Max Kills: 5
  Time Limit: 30
  # Possible variables are <player> and <victim>
  Commands on Abuse:
    - 'kick <player> &cKill Abuse Is Not Allowed!'
  Respawn Protection: 3

# Section with settings triggered when a player kills another player
# Money Reward - Money won as reward, use less or equal to 1 for percentage like 0.05 for 5%, 1 for 100% (0 to disable)
# Money Penalty - Money lost on PvP death, use less or equal to 1 for percentage like 0.1 for 10%, 1 for 100% (0 to disable)
# Money Steal - Should the amount won from money reward be stolen from the dead player
# WorldGuard Exclusions - WorldGuard regions where rewards, penalties and commands will not be executed
Player Kills:
  Money Reward: 0.0
  Money Penalty: 0.0
  Money Steal: false
  # Commands to execute on kill (<player> is the killer, <victim> is the victim, <item> is the item material in hand)
  Commands On Kill:
    - 'examplecommand <player> killed <victim> with <item>'
  WorldGuard Exclusions:
    - 'exampleregion'

# Section for PvP Toggle command - /pvp
# Players can't use the command unless they have permission
# Cooldown - How many seconds until players can use the command again
# NameTags - What should the player's prefix be when pvp is on/off
# You can write 'none' to disable one of the nametags, or set 'Enabled' to false to disable both
# Commands -> Command list to execute on PvP toggle, use '%p' for player name
# WorldGuard Overrides -> PvP Toggle is forcibly enabled on an attack in all regions with WG's pvp flag set to allow
# WorldGuard overrides region list -> PvP Toggle is forcibly enabled on an attack in the listed regions, regardless of the WG's pvp flag
PvP Toggle:
  Cooldown: 15
  NameTags:
    Enabled: false
    Prefix On: '&1'
    Prefix Off: '&2'
  # This setting runs every hour and applies a money fee to every player with PvP disabled, it's a very simplified system 
  # so it doesn't track how long PvP has been off for that player. Leave as 0 to disable
  PvP Disabled Money Fee: 0
  Commands PvP On:
    - 'examplecommand %p turned pvp on'
  Commands PvP Off:
    - 'examplecommand %p turned pvp off'
  WorldGuard Overrides: true
  WorldGuard Overrides Region List:
    - 'example'

# Section to configure interactions with other plugins
Plugin Hooks:
  Essentials:
    # Should AFK players be protected from other players
    Protect AFK: true
  Kingdoms:
    # Disable PvP and newbie protection if the players are in an invasion
    No Protection In War: true
  SimpleClans:
    # Disable PvP and newbie protection if the players are in a SimpleClans war
    No Protection In War: true
  Towny:
    # Disable PvP and newbie protection if the players are in a siege war
    No Protection In War: true
    # Essentially only pushes back if a town is peaceful, it ignores if the town PvP is on or off, can be useful to prevent traps
    Pushback on Peaceful: false
  CooldownsX:
    # Change this into the cooldown id for enderpearls in CooldownsX, by default they have it as exampleOne in cooldowns.yml
    # If setup correctly PvPManager will use a different cooldown while in combat and then revert back to CooldownsX
    Enderpearl: exampleOne

Database:
  # Database type, supported databases: SQLite or MySQL
  Type: SQLite
  # Only fill this section if using MySQL
  MySQL:
    Host: 127.0.0.1
    Port: 3306
    Username: root
    Password: '12345'
    Database: minecraft

# Should PvPManager be allowed to check for updates and tell you about them
# Auto Update - After checking should we download it automatically for you?
Update Check:
  Enabled: true
  Auto Update: true

Metrics:
  Opt-out: false
  
# Potions considered harmful, players will be tagged by them and protected from them
# See list here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
Harmful Potions:
  - SLOW
  - SLOWNESS # SLOW 1.20.5+
  - SLOW_DIGGING
  - MINING_FATIGUE # SLOW_DIGGING 1.20.5+
  - CONFUSION
  - NAUSEA # CONFUSION 1.20.5+
  - BLINDNESS
  - HUNGER
  - WEAKNESS
  - POISON
  - WITHER
  - GLOWING
  - LEVITATION
  - UNLUCK
  - BAD_OMEN
  - INFESTED

Debug Mode: false

# Informs PvPManager if the config is updated, do not touch it unless you want to reset the config
Config Version: ${config.version}
Database Version: ${database.version}
