name: ${project.name}
main: ${project.groupId}.PvPManager
version: ${project.version}
author: ChanceSD
website: https://www.spigotmc.org/resources/pvpmanager-lite.845/
description: ${project.description}
api-version: 1.13
folia-supported: true

softdepend:
  - Vault
  - WorldGuard
  - LibsDisguises
  - SimpleClans
  - EZRanksLite
  - Essentials
  - PlaceholderAPI
  - GriefPrevention
  - Towny
  - HuskTowns
  - HuskClaims
  - Kingdoms
  - TAB

libraries:
  - com.zaxxer:HikariCP:4.0.3
  - org.slf4j:slf4j-api:2.0.13 # for MC 1.8

commands:
   pvpmanager:
      description: Shows the main PvPManager help page
      aliases: [pm, pvpm, pmr]
   pvp:
      description: Toggles PvP status
      aliases: [togglepvp, pvptoggle]
      usage: "Usage: /<command> [on|off] or /<command> [player] [on|off]"
   newbie:
      description: Check time left as a newbie or force disable newbie
      aliases: [newbietime]
      usage: "Usage: /<command> add/checktime/remove [name] or /<command> disable"
   pvpoverride:
      description: Allows the player to attack everyone everywhere
      aliases: [pvpo]
      permission: pvpmanager.override
   pvpinfo:
      description: Allows the player to see his or others information
      aliases: [pvpi]
      permission: pvpmanager.info
      usage: "Usage: /<command> [player]"
   pvpstatus:
      description: Allows the player to see his or others pvp status
      aliases: [pvps, pstatus]
      permission: pvpmanager.pvpstatus.self
      usage: "Usage: /<command> [player]"
   pvplist:
      description: List the PvP state of all online or offline players
      aliases: [plist, pvpl]
      permission: pvpmanager.list
   pvptag:
      description: Shows time left until out of combat or tag player
      aliases: [ct, ctag, combattag]
   untag:
      description: Untags a player  
      permission: pvpmanager.admin
      usage: "Usage: /<command> <player>"
   announce:
      description: Broadcasts a message to all players with color support
      permission: pvpmanager.admin
   pvpglobal:
      description: Toggle PvP for the whole server
      permission: pvpmanager.admin
      usage: "Usage: /<command> <on|off>"

permissions:
   pvpmanager.*:
     description: Gives access to all PvPManager features
     default: op
     children:
       pvpmanager.admin: true
   pvpmanager.admin:
     description: Gives access to admin features
     default: false
     children:
       pvpmanager.reload: true
       pvpmanager.user: true
       pvpmanager.override: true
       pvpmanager.info: true
       pvpmanager.info.others: true
       pvpmanager.pvpstatus.nocooldown: true
   pvpmanager.exempt:
     description: Exempts player from consequences during combat
     default: false
     children:
       pvpmanager.nocombattag: true
       pvpmanager.nocombatlog: true
       pvpmanager.nodisable: true
       pvpmanager.nokillabuse: true
   pvpmanager.user:
     description: Gives access to features appropriate for average users
     default: false
     children:
       pvpmanager.pvpstatus.change: true
       pvpmanager.pvpstatus.self: true
       pvpmanager.pvpstatus.others: true
       pvpmanager.list: true
       pvpmanager.menu: true
   pvpmanager.pvpstatus.nocooldown:
     description: No cooldown for pvp toggle command
     default: false
   pvpmanager.pvpstatus.change:
     description: Allows you to change your PvP status between <on> and <off>
     default: false
   pvpmanager.reload:
     description: Allows acess to the PvPManager reload command
     default: false
   pvpmanager.nocombattag:
     description: Exempts a player from being tagged in combat
     default: false
   pvpmanager.nocombatlog:
     description: Exempts a player from combat log punishments
     default: false
   pvpmanager.override:
     description: Players with this permission can use the pvp override command and attack everywhere
     default: false
   pvpmanager.nodisable:
     description: Players with this permission don't get fly and gamemode disabled
     default: false
   pvpmanager.nokillabuse:
     description: Players with this permission don't get punished by kill abuse
     default: false
   pvpmanager.exempt.block.commands:
     description: Players with this permission can use commands while tagged
     default: false
   pvpmanager.bypass.protection.respawn:
     description: Players with this permission do not get respawn protection
     default: false 
   pvpmanager.list:
     description: Allows access to the list of players with PvP enabled and disabled
     default: false
   pvpmanager.menu:
     description: Allows access to the PvPManager help menu
     default: false
   pvpmanager.info.others:
     description: Allows using the PvPManager info command to check other player's info
     default: false
